add buttonIcon
janis-commerce/ui-web pull request #18
Opened 2023-12-11 13:50 UTC by Mauroskyer

**Link al ticket**
https://janiscommerce.atlassian.net/browse/JMV-2749

**Descripción del requerimiento**

Se requiere agregar del [package web ui](https://github.com/janis-commerce/ui-web), varios de los componentes bases que ya están en el repo:

Migrar estos componente Icon y Button

**Descripción de la solución**

se creo una clase en el componente icon, para que este ya no dependa del svg del Icon.

Cómo se puede probar?

En este repo:

- Eliminar node_modules y package-lock.json
- Ingresar a la branch, tirar yarn, linkear con yalc el package (instalarlo primero con npm i yalc -g)
- Tirar yarn build para buildear el package
- Tirar yalc publish

En views:

- Eliminar node_modules y package-lock.json
- Agregar el package (yalc add @janisscommerce/ui-web) y ejecutar npm i (esto agregará la carpeta .yalc al repo)
- En la carpeta del componente Button, agregar un archivo styles.js para importar el Chip desde el package, declarar un styled component y agregarle algunos estilos
- En Button.js o en Icon.js, eliminar la importación del package e importar el componente desde el archivo de estilos creado.
- Probar en local en alguna vista donde haya un button/icon (o utilizar el playground)

2023-12-11 14:19 UTC, dgiannico19 requested changes
Mau fijate que está rebotando un test con tu cambio

2023-12-12 21:37 UTC, Mauroskyer commented
@dgiannico19  ya pasa todos los tests.

2023-12-13 13:23 UTC, dgiannico19 commented
@Mauroskyer Segun leo en la descripción, hay que migrar tmb Icon, por ahora veo que Icon de ui-web tiene ciertas diferencias con el de Views, está bien que quede ese? o deberias modificarlo a como esta el de Views? Porque el de Views despues va a tomar ese

2023-12-13 22:07 UTC, Mauroskyer commented
@dgiannico19  ya hice los cambios que quedamos, me avisas para ver lo del ui-web

2023-12-14 19:59 UTC, dgiannico19 commented
PRobe colocando archivos desde Views directo del packages y funcionan editables bien

2023-12-14 20:00 UTC, dgiannico19 approved these changes
Probé importando desde ui-web en Views y me lo toma sin drama y me detecta bien los cambios

2023-12-19 17:42 UTC, fiorafran commented
Funciona joya en views
![image](https://github.com/janis-commerce/ui-web/assets/80725782/a7989ff2-d941-4b67-942d-ddd06373eba5)
ejemplo cambiando colores:
![image](https://github.com/janis-commerce/ui-web/assets/80725782/01b6ddd0-e453-4d8d-90c1-285c44b66285)
![image](https://github.com/janis-commerce/ui-web/assets/80725782/1d59e882-9a7b-4009-8175-3ffc775829d0)

2023-12-19 17:43 UTC, fiorafran approved these changes

2023-12-20 22:19 UTC, FranciscoZapa commented
Reemplazando el componente Button de Views por el de Ui-web no me settea correctamente el color del icono interno de los buttons, me falta agregar algo @Mauroskyer ?
![image](https://github.com/janis-commerce/ui-web/assets/7831086/97937345-a09c-4e7c-92e3-bb48b3d7fc4b)

2023-12-21 19:01 UTC, FranciscoZapa approved these changes
Probe cambiando los colores y lo toma bien 
![image](https://github.com/janis-commerce/ui-web/assets/7831086/2b9f5f1e-9c6a-45e3-85aa-1ff94fc0cba1)
Dejando sin cambios toma bien los colores 
![image](https://github.com/janis-commerce/ui-web/assets/7831086/f64e3d73-ad81-485e-94d8-3c0443fcc9e1)
Aplicandole iconColor cambia el color solo del icono
![image](https://github.com/janis-commerce/ui-web/assets/7831086/f4c1c5ae-2876-4329-990b-8410619bc2fc)

2023-12-28 13:15 UTC, colomfernando commented on src/components/Button/styles.js
> +	Children: styled.div``
para que usamos ese Children @Mauroskyer ? no lo veo implementado

2023-12-28 15:18 UTC, Mauroskyer commented on src/components/Button/styles.js
> +	Children: styled.div``
ya lo saco, se me quedo de una corrección que hice la ultima vez

2023-12-28 15:56 UTC, colomfernando reviewed
@Mauroskyer ademas revisate storybooks que esta fallando al querer levantarlo por un error de que se esta importando algo que no existe en el componente Link

2023-12-28 15:56 UTC, colomfernando commented on src/components/Button/styles.js
> +		${(props) => {
estaria bueno @Mauroskyer mejorar este switch. Podriamos tener una funcion y un objeto con cada key para tener separado en base a la variante que estilos aplicar. De esa manera seria mas legible

2024-01-02 18:54 UTC, dgiannico19 commented on src/components/Button/styles.js
> +import { getColor, getHoverColor, getPressedColor, buttonVariants } from './utils';
@Mauroskyer getCOlor, getHoverColor y getPressedColor ya no se usan en el componente, se podrian borrar q importe solo buttonVariants

2024-01-02 18:55 UTC, dgiannico19 commented on src/components/Button/styles.js
>  import { getColor as findColorInTheme, timingFunctions } from 'theme/utils';
@Mauroskyer css no se usa mas en este archivo se podria borrar {css}

2024-01-03 14:27 UTC, fiorafran commented
Lo estoy intentando usar en views y me rompe por todos lados

2024-01-03 15:30 UTC, fiorafran commented
Ya lo pude correr, pero tengo problemas con fontColor

2024-01-04 23:26 UTC, Mauroskyer commented
@fiorafran  @dgiannico19 @FranciscoZapa  ya pueden probar el componente.

2024-01-05 13:20 UTC, dgiannico19 commented on src/components/Button/utils.js
> +		contained: (props) => css`
@Mauroskyer aca entiendo que no hace falta pasarle props a la funcion ya que los recibe arriba en getButtonStyles

2024-01-05 13:20 UTC, dgiannico19 commented on src/components/Button/utils.js
> +		outlined: (props) => css`
@Mauroskyer aca entiendo que no hace falta pasarle props a la funcion ya que los recibe arriba en getButtonStyles

2024-01-05 13:20 UTC, dgiannico19 commented on src/components/Button/utils.js
> +		cleaned: (props) => css`
@Mauroskyer aca entiendo que no hace falta pasarle props a la funcion ya que los recibe arriba en getButtonStyles

2024-01-05 13:23 UTC, dgiannico19 commented on src/components/Button/utils.js
> +export const getButtonStyles = (props) => {
@Mauroskyer Por un tema de legibilidad no te parece destructurar las props y traer solo color, fontColor y variant y sacar los "props." de toda la funcion?
Yo haria lo mimso con colors. un destructuring arriba que saque const {los colores que se usan } = colors y sacaria todos los colors. viendo que se usa 12 veces el colors, pero queda a tu criterio

2024-01-08 22:48 UTC, Mauroskyer commented
@fiorafran  @dgiannico19  @FranciscoZapa  @colomfernando @Sebaavt95  ya esta funcionando storybook

2024-01-09 13:49 UTC, dgiannico19 commented
@Mauroskyer fijate que en el storybook de Button los botones blancos que tienen iconos, el icono está en blanco tmb, me parece que quedaría mejor ponerle un  iconColor para que se pinten esos iconos y queden mejor para ver, no se que te parece
Asi esta ahora
![image](https://github.com/janis-commerce/ui-web/assets/64233677/99483916-720a-4e8c-a979-ab8a2bdb6ee4)
Asi se ven con un color 
![image](https://github.com/janis-commerce/ui-web/assets/64233677/32ef303d-3650-40e6-b8a0-ecc02df89ed6)

2024-01-09 14:13 UTC, Mauroskyer commented
@dgiannico19 echo los cambios

2024-01-09 14:21 UTC, dgiannico19 commented on src/components/Link/Link.stories.mdx
>  <Meta title="JANIS/Front/components/Link" component={Link} />
@Mauroskyer fijate que el Link lo estas mostrando en una nueva tab llamada Janis, deberías cambiar la etiqueta Meta para que se renderice dentro de components, algo asi:
<Meta title="Components/Link" component={Link} />

Sin el cambio se ve aca:
![image](https://github.com/janis-commerce/ui-web/assets/64233677/a1484b76-7870-4c7e-a146-4ae66ffeee85)


Con el cambio se ve ahi
![image](https://github.com/janis-commerce/ui-web/assets/64233677/92f7e08b-a25a-4d80-a050-acf6a13c2f13)

2024-01-09 15:04 UTC, Mauroskyer commented
@dgiannico19 echo los cambios

2024-01-09 16:07 UTC, dgiannico19 commented
@Mauroskyer viendo el storybook de Icon: http://localhost:6006/?path=/story/components-icon--icon
solo para que quede mas lindo se le podria agregar un margen izquierdo como tiene el Button, no se que te parece, pero ahoa se ve asi:
![image](https://github.com/janis-commerce/ui-web/assets/64233677/622c3852-ebe5-4c97-ae0e-5b96100e98f6)

con un margen como el del componente button asi:
![image](https://github.com/janis-commerce/ui-web/assets/64233677/ae2f596f-b6ea-4109-a5e0-f9d76b7ff27d)
Me parece que queda un poco mejor no se que opinas

2024-01-09 19:01 UTC, dgiannico19 requested changes
Deje comentarios

2024-01-09 19:46 UTC, Mauroskyer commented
Cambios los casos del button storybook : 
![image](https://github.com/janis-commerce/ui-web/assets/57736533/2c6202d3-3eab-4734-9c24-a265a8263486)

Cambios en los casos del Icon storybook : 
![image](https://github.com/janis-commerce/ui-web/assets/57736533/a44629f1-6082-4318-b2fd-b75ae221a3ed)

2024-01-09 21:11 UTC, dgiannico19 approved these changes
Bueno ahora si, veo todo funcionando, los cambios desde el lado de views los toma bien, tener en cuenta que en views hay que levantar la rama JMV-2928

2024-01-10 17:28 UTC, FranciscoZapa approved these changes
Storybook funciona correctamente 
![image](https://github.com/janis-commerce/ui-web/assets/7831086/4a5e2910-c7dd-46a5-9e75-c9d9b8763b67)
Toma correctamente props para cambiar estilos 
![image](https://github.com/janis-commerce/ui-web/assets/7831086/b32d1826-86ee-4060-9be5-a74383c68d38)
tambien quedo bien agregado Link 
![image](https://github.com/janis-commerce/ui-web/assets/7831086/1cd83eca-56b9-46dd-b2b0-be544e379345)

2024-01-12 14:16 UTC, fiorafran approved these changes
Funciona, levanta storybooks, y cambia segun las props 
![image](https://github.com/janis-commerce/ui-web/assets/80725782/21ea2312-dab7-45d5-9b40-0569943af574)

2024-01-15 17:16 UTC, Sebaavt95 approved these changes
@Mauroskyer Dejo evidencia de la review:

Storybooks levanta bien:
![image](https://github.com/janis-commerce/ui-web/assets/59315051/fc4adf63-8711-4a20-8dc2-95515373b732)

Cambia según las props:
![image](https://github.com/janis-commerce/ui-web/assets/59315051/b544f2ce-ec6e-401a-a6c6-6662fb45d3a7)

2024-01-23 17:30 UTC, merged