add control to missing components
janis-commerce/ui-web pull request #22
Opened 2024-02-01 16:09 UTC by dgiannico19

**Link al ticket**
https://janiscommerce.atlassian.net/browse/JMV-3258

**Descripción del requerimiento**
Se requiere que funcione la función de control en storybook, los componentes a corregir en este PR son Checkbox,  Color, ColorPicker, HTML, Image, Input, QRCode, Switch y Textarea

**Descripción de la solución**
Se modificaron los archivos de mdx a js para que funcione al funcion control, No se tuvo en cuenta errores o probelmas en cada componente sino que solamente que funcione el control

**Cómo se puede probar?**
* Ingresando a Ui web, en la rama del PR
* Levantando el proyecto con 'npm run storybook'
* probando el control de dichos componentes

**Screenshot**
![image](https://github.com/janis-commerce/ui-web/assets/64233677/9f4fe8d8-7801-434c-a003-b956745aba77)

**Datos extra a tener en cuenta**

- No se tuvo en cuenta errores o problemas que pueda haber en cada componente sino que solamente que funcione el control

2024-02-01 17:30 UTC, Sebaavt95 approved these changes
@dgiannico19 Los controles de los componentes mencionados funcionan OK. Dejo loom:
https://www.loom.com/share/0e8f01206b9d47d9a6d2ee5b57f223e9?sid=72439e49-9d6a-4dfd-b798-5c4a1295f1a5

2024-02-01 18:57 UTC, fiorafran commented
Lo veo ok
![image](https://github.com/janis-commerce/ui-web/assets/80725782/d84216a7-5e8e-4d62-9b6f-cf20dc74fa25)
![image](https://github.com/janis-commerce/ui-web/assets/80725782/f59c601d-8c06-4e43-a3fc-56ed64627604)
![image](https://github.com/janis-commerce/ui-web/assets/80725782/f2de9699-7662-4360-8871-ae77afef5fbb)

2024-02-01 18:57 UTC, fiorafran approved these changes

2024-02-01 21:28 UTC, FranciscoZapa requested changes
Se reviso los diferentes componentes y los veo genial casi a todos
Checkbox
![image](https://github.com/janis-commerce/ui-web/assets/7831086/8b582af4-5abc-4d59-a7e3-dde777b54b0f)
Color
![image](https://github.com/janis-commerce/ui-web/assets/7831086/3b00f49c-9f33-47ba-a2c1-0687af82710f)
ColorPicker
![image](https://github.com/janis-commerce/ui-web/assets/7831086/7b2be862-2518-4ee2-ac39-14d8fe3d942c)
HTML
![image](https://github.com/janis-commerce/ui-web/assets/7831086/6930294c-3cea-4736-8b01-2e7204651da9)
Image
![image](https://github.com/janis-commerce/ui-web/assets/7831086/601515b6-a76c-45af-a0be-94241f14732b)
QRCode
![image](https://github.com/janis-commerce/ui-web/assets/7831086/af3d03dc-b7db-4c18-a5f2-30e63e3d975b)
TextArea
![image](https://github.com/janis-commerce/ui-web/assets/7831086/4a1c045a-9b1d-4c1b-be6a-86134dfc2d92)

Excepto Image donde el selector de Icon no se esta mostrando como en los otros casos que estaba mas chevere con el selector
![image](https://github.com/janis-commerce/ui-web/assets/7831086/0c30cb30-e561-4dd2-acec-9edd4c694a28)
El Switch igual estaria bueno que el checked sea un switch como en las otras props en vez de tener que escribir false o true
![image](https://github.com/janis-commerce/ui-web/assets/7831086/7283c177-492a-463d-8225-eb912fe803f7)

2024-02-01 21:42 UTC, dgiannico19 commented
> Se reviso los diferentes componentes y los veo genial casi a todos Checkbox ![image](https://private-user-images.githubusercontent.com/7831086/301650051-8b582af4-5abc-4d59-a7e3-dde777b54b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDA1MS04YjU4MmFmNC01YWJjLTRkNTktYTdlMy1kZGU3NzdiNTRiMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFiYTQ3YzhlYjFkMTMzN2IwMDQyOTJjM2NkZTY2YWUwODU1Mzg4N2NkMDNkOWY1ZmRiODEyN2JjMTBhYjIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KdQ4eEKneV9yaeRMLkHF-s2MtpSqvGJoMT9xLwRpi-E) Color ![image](https://private-user-images.githubusercontent.com/7831086/301650096-3b00f49c-9f33-47ba-a2c1-0687af82710f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDA5Ni0zYjAwZjQ5Yy05ZjMzLTQ3YmEtYTJjMS0wNjg3YWY4MjcxMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2ZDYzOWViMDBjZmEyODk5NmMzZjgxOTE2MWRjOTc2OTZjYTIzZjg2OWJlNmMwOTAwNTE0YzdjODMwZjNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.edrr_clLemM9ZYcjpgoN3a0B0dkY_rizcWZhTz6yZks) ColorPicker ![image](https://private-user-images.githubusercontent.com/7831086/301650318-7b2be862-2518-4ee2-ac39-14d8fe3d942c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDMxOC03YjJiZTg2Mi0yNTE4LTRlZTItYWMzOS0xNGQ4ZmUzZDk0MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FkMTU2NTU3YzA5OGI1NDM2ZDhhOWNjOWQ4MmEwYTM0YjNiZWFlNDNhMjMwMTI1YWM5NTRmZWE4M2U3N2M3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nr4Mu624X1hspO1IbNkK4Cl00xb_lni9BvQZFvkDmZw) HTML ![image](https://private-user-images.githubusercontent.com/7831086/301650589-6930294c-3cea-4736-8b01-2e7204651da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDU4OS02OTMwMjk0Yy0zY2VhLTQ3MzYtOGIwMS0yZTcyMDQ2NTFkYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FjMDRlNmViN2EwOWViZjIxOTMyM2ZkYjY0MDI3ZjhjMjk2OTAyNjY0MzA1NjFkMjljOGY2NjA3ZTgyNmI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l04iJYQ13kVveF9emdPc3h4ypFm4soCnOYBZSI0Fdq0) Image ![image](https://private-user-images.githubusercontent.com/7831086/301650803-601515b6-a76c-45af-a0be-94241f14732b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDgwMy02MDE1MTViNi1hNzZjLTQ1YWYtYTBiZS05NDI0MWYxNDczMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ3MjI1N2NlNDY1MGIxNWRhNWJmOWYyNDJlN2FmYWUzZmY5MGYyYjQzNzViY2I3NTg2YjljNjkwNmNjOWMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E3ZVq3KsKtoXnI6O5xfrpetJErqfNP7ZfvCoREU7Nt0) QRCode ![image](https://private-user-images.githubusercontent.com/7831086/301651236-af3d03dc-b7db-4c18-a5f2-30e63e3d975b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTIzNi1hZjNkMDNkYy1iN2RiLTRjMTgtYTVmMi0zMGU2M2UzZDk3NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlODBlYjc3ZjhjMDc3ZjUxOGE1YzczY2RmYTczMzhlOWMwNjhjNmE1MjUyZmFkZTA3OGMwM2E3NWJhZjUzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IYLmRMWWIlNySWemQuMadGdvRYMX_JLe7fKzMrznqCY) TextArea ![image](https://private-user-images.githubusercontent.com/7831086/301651698-4a1c045a-9b1d-4c1b-be6a-86134dfc2d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTY5OC00YTFjMDQ1YS05YjFkLTRjMWItYmU2YS04NjEzNGRmYzJkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZjZGU5ZTJkMmYwNDhmMWIwNDRmNGIxNDUzOWU2ZjEwZGYzNGNkYzYwOGMxMDk2NzQ4ZDU4NWJjMzM5MjNmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1IA7ZbgI3h9Ts7tZSy7mJvmLEvdFPWgDOiKQKC9T28)
> 
> Excepto Image donde el selector de Icon no se esta mostrando como en los otros casos que estaba mas chevere con el selector ![image](https://private-user-images.githubusercontent.com/7831086/301651018-0c30cb30-e561-4dd2-acec-9edd4c694a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTAxOC0wYzMwY2IzMC1lNTYxLTRkZDItYWNlYy05ZWRkNGM2OTRhMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVlZDVkNTFkMDMxMjQwNTlhY2JlMzUzZWQwNjFhYzgxZDQyNzcwYjNlZWIyNzgzODYxZjkzYTRhOTRkOTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zn8ynL8T_3WIBHE1Ijm0l01PukaBOsmyZVAdbOWMiv0) El Switch igual estaria bueno que el checked sea un switch como en las otras props en vez de tener que escribir false o true ![image](https://private-user-images.githubusercontent.com/7831086/301651444-7283c177-492a-463d-8225-eb912fe803f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTQ0NC03MjgzYzE3Ny00OTJhLTQ2M2QtODIyNS1lYjkxMmZlODAzZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjYxYjU1NDcxMTUxNTRmYTU1ZWEyNzAyNWRmYjMzODhjOTM1ZDU1ZmZlNDk3ZTA4ODc4NmIzMmE2ZTQ3YWYyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t2XeJvmWguUGh2NFH5qzbvCy4v5mifxpS57Za3Nc0b4)

@FranciscoZapa el tema es que son cambios sobre los componentes en si, para que muestre los iconos la proptype de icon debería no ser un strign sino un PropTypes.oneOf(Object.keys [...]

2024-02-01 21:45 UTC, FranciscoZapa commented
> > Se reviso los diferentes componentes y los veo genial casi a todos Checkbox ![image](https://private-user-images.githubusercontent.com/7831086/301650051-8b582af4-5abc-4d59-a7e3-dde777b54b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDA1MS04YjU4MmFmNC01YWJjLTRkNTktYTdlMy1kZGU3NzdiNTRiMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFiYTQ3YzhlYjFkMTMzN2IwMDQyOTJjM2NkZTY2YWUwODU1Mzg4N2NkMDNkOWY1ZmRiODEyN2JjMTBhYjIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KdQ4eEKneV9yaeRMLkHF-s2MtpSqvGJoMT9xLwRpi-E) Color ![image](https://private-user-images.githubusercontent.com/7831086/301650096-3b00f49c-9f33-47ba-a2c1-0687af82710f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDA5Ni0zYjAwZjQ5Yy05ZjMzLTQ3YmEtYTJjMS0wNjg3YWY4MjcxMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2ZDYzOWViMDBjZmEyODk5NmMzZjgxOTE2MWRjOTc2OTZjYTIzZjg2OWJlNmMwOTAwNTE0YzdjODMwZjNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.edrr_clLemM9ZYcjpgoN3a0B0dkY_rizcWZhTz6yZks) ColorPicker ![image](https://private-user-images.githubusercontent.com/7831086/301650318-7b2be862-2518-4ee2-ac39-14d8fe3d942c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDMxOC03YjJiZTg2Mi0yNTE4LTRlZTItYWMzOS0xNGQ4ZmUzZDk0MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FkMTU2NTU3YzA5OGI1NDM2ZDhhOWNjOWQ4MmEwYTM0YjNiZWFlNDNhMjMwMTI1YWM5NTRmZWE4M2U3N2M3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nr4Mu624X1hspO1IbNkK4Cl00xb_lni9BvQZFvkDmZw) HTML ![image](https://private-user-images.githubusercontent.com/7831086/301650589-6930294c-3cea-4736-8b01-2e7204651da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDU4OS02OTMwMjk0Yy0zY2VhLTQ3MzYtOGIwMS0yZTcyMDQ2NTFkYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FjMDRlNmViN2EwOWViZjIxOTMyM2ZkYjY0MDI3ZjhjMjk2OTAyNjY0MzA1NjFkMjljOGY2NjA3ZTgyNmI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l04iJYQ13kVveF9emdPc3h4ypFm4soCnOYBZSI0Fdq0) Image ![image](https://private-user-images.githubusercontent.com/7831086/301650803-601515b6-a76c-45af-a0be-94241f14732b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MDgwMy02MDE1MTViNi1hNzZjLTQ1YWYtYTBiZS05NDI0MWYxNDczMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ3MjI1N2NlNDY1MGIxNWRhNWJmOWYyNDJlN2FmYWUzZmY5MGYyYjQzNzViY2I3NTg2YjljNjkwNmNjOWMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E3ZVq3KsKtoXnI6O5xfrpetJErqfNP7ZfvCoREU7Nt0) QRCode ![image](https://private-user-images.githubusercontent.com/7831086/301651236-af3d03dc-b7db-4c18-a5f2-30e63e3d975b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTIzNi1hZjNkMDNkYy1iN2RiLTRjMTgtYTVmMi0zMGU2M2UzZDk3NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlODBlYjc3ZjhjMDc3ZjUxOGE1YzczY2RmYTczMzhlOWMwNjhjNmE1MjUyZmFkZTA3OGMwM2E3NWJhZjUzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IYLmRMWWIlNySWemQuMadGdvRYMX_JLe7fKzMrznqCY) TextArea ![image](https://private-user-images.githubusercontent.com/7831086/301651698-4a1c045a-9b1d-4c1b-be6a-86134dfc2d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTY5OC00YTFjMDQ1YS05YjFkLTRjMWItYmU2YS04NjEzNGRmYzJkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZjZGU5ZTJkMmYwNDhmMWIwNDRmNGIxNDUzOWU2ZjEwZGYzNGNkYzYwOGMxMDk2NzQ4ZDU4NWJjMzM5MjNmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l1IA7ZbgI3h9Ts7tZSy7mJvmLEvdFPWgDOiKQKC9T28)
> > Excepto Image donde el selector de Icon no se esta mostrando como en los otros casos que estaba mas chevere con el selector ![image](https://private-user-images.githubusercontent.com/7831086/301651018-0c30cb30-e561-4dd2-acec-9edd4c694a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTAxOC0wYzMwY2IzMC1lNTYxLTRkZDItYWNlYy05ZWRkNGM2OTRhMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVlZDVkNTFkMDMxMjQwNTlhY2JlMzUzZWQwNjFhYzgxZDQyNzcwYjNlZWIyNzgzODYxZjkzYTRhOTRkOTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zn8ynL8T_3WIBHE1Ijm0l01PukaBOsmyZVAdbOWMiv0) El Switch igual estaria bueno que el checked sea un switch como en las otras props en vez de tener que escribir false o true ![image](https://private-user-images.githubusercontent.com/7831086/301651444-7283c177-492a-463d-8225-eb912fe803f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMzMjMsIm5iZiI6MTcwNjgyMzAyMywicGF0aCI6Ii83ODMxMDg2LzMwMTY1MTQ0NC03MjgzYzE3Ny00OTJhLTQ2M2QtODIyNS1lYjkxMmZlODAzZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjEzMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjYxYjU1NDcxMTUxNTRmYTU1ZWEyNzAyNWRmYjMzODhjOTM1ZDU1ZmZlNDk3ZTA4ODc4NmIzMmE2ZTQ3YWYyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t2XeJvmWguUGh2NFH5qzbvCy4v5mifxpS57Za3Nc0b4)
> 
> @FranciscoZapa el tema es que son cambios sobre los componentes en si, para que muestre los iconos la proptype de icon debería no ser un strign sino un PropTypes.oneOf(Object [...]

2024-02-01 21:46 UTC, FranciscoZapa reviewed
En base a la explicacion de dami estaria todo ok

2024-02-01 21:51 UTC, FranciscoZapa approved these changes
En base a la explicacion de dami estaria todo ok

2024-02-07 13:24 UTC, Mauroskyer commented
![image](https://github.com/janis-commerce/ui-web/assets/57736533/3c8e6be0-8116-4674-8417-c090ac72d965)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/3e5c191f-3123-4680-93bd-f194d300db1a)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/74627c15-fa8d-41f2-9988-dd0112123030)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/56fc0c68-3e2b-4696-af10-f4c9472a9ad3)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/4cf031c6-d161-4642-b453-cb14c0931b31)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/ee70d74f-ccf3-46d2-ab03-a2525b9e448b)
lo veo ok

2024-02-07 13:24 UTC, Mauroskyer approved these changes

2024-02-09 13:13 UTC, merged