Jmv 3257 button icon theme UI web
janis-commerce/ui-web pull request #24
Opened 2024-02-08 16:24 UTC by dgiannico19

**Link al ticket**
https://janiscommerce.atlassian.net/browse/JMV-2773

**Descripción del requerimiento**
Mejorar e implementar el Boton y ek Icon de Ui web en Views

**Descripción de la solución**

- Se unificó la paleta de colores ViewsPalette
- Se corrigió el utils de Button para las variables del boton y se eliminó getColors para usar findColorInPalette
- Se arreglaron test que usaban getColors y la importación de ViewsPalette

**Como se puede probar**
Desde ui-web, se puede probar accediendo a storybook con el comando "npm run storybook" y probando las distinas variables desde la tag Docs del Button, lo mismo del Icon
**Icon:**
![image](https://github.com/janis-commerce/ui-web/assets/64233677/bfe2a7e6-3a24-4f6c-9d4c-36b550bf110f)

**Button**
![image](https://github.com/janis-commerce/ui-web/assets/64233677/647d6ddb-bd72-4115-b9b4-b6daf0d06808)

Para probarlo en Views:

- Desde Ui-web,
Borrar node_modules, package-lock y yarn-lock
Correr comando "yarn", esto genera el yarn lock nuevo e instala dependencias
Correr comando "yarn build" que crea la carpeta dist
Correr comando "yalc publish" para hacer publica la versión del paquete
**Nada mas desde Ui-web**

- Desde Views
Levantar la rama de views JMV-3257-buttonicon-theme-ui-web
Borrar node_modules ni package-lock.json, 
correr comando  "yalc add @janiscommerce/ui-web" - Esto creara la carpeta yalc con el paquete adentro, y en el pakage.json realiza el cambio del paquete que quedaría asi: "@janiscommerce/ui-web": "file:.yalc/@janiscommerce/ui-web",
correr comando "npm i"
Levantar el docker y deberíamos estar usando el paquete en local

**Para realizar cambios desde el paquete,** 
- Hacer el cambio necesario en ui-web
- Correr comando "yarn build"
- Correr comando "yalc push"

**A tener en cuenta**
La rama de Views tiene cambios que son necesarios para que funcione todo bien, aunque no se pushea aun ya que requiere nueva version del paquete

2024-02-08 17:45 UTC, Sebaavt95 commented on src/theme/utils.js
> +const findColorInPalette = (color) => palette[color] || color;
@dgiannico19 A la función `findColorInPalette` le dejaría el nombre anterior (`getColor`) porque hay archivos donde solo el cambio es el nombre. Donde debería exportarse con otro nombre sería en Button/utils.js

2024-02-08 17:46 UTC, Sebaavt95 commented on src/components/Button/utils.js
> -import { getColor as findColorInTheme } from 'theme/utils';
@dgiannico19 Así

2024-02-08 17:47 UTC, Sebaavt95 requested changes
@dgiannico19 Dejé dos comentarios en el código

2024-02-08 18:12 UTC, Sebaavt95 approved these changes
Probado y funcionando OK
https://www.loom.com/share/05b331d258914182a45300c7515d42fc?sid=057d496a-b388-49dc-8814-92e5ac4cc844

2024-02-08 22:02 UTC, fiorafran commented on src/components/Button/utils.js
> +			color: ${fontColor ? findColorInTheme(fontColor) : white};
aca no seria `findColorInTheme(fontColor || 'white')` ?

2024-02-09 12:10 UTC, dgiannico19 commented on src/components/Button/utils.js
> +			color: ${fontColor ? findColorInTheme(fontColor) : white};
Tenes razon @fiorafran! corregido listo para revisión

2024-02-09 15:04 UTC, fiorafran commented
Lo veo joya ✅ 
![image](https://github.com/janis-commerce/ui-web/assets/80725782/363c3c03-454c-4e4e-8baa-337df81b0fb1)
![image](https://github.com/janis-commerce/ui-web/assets/80725782/17e4a41b-59af-4fb0-b16b-c7c0bb4a7e0e)

2024-02-09 15:04 UTC, fiorafran approved these changes

2024-02-16 14:44 UTC, Mauroskyer commented
Lo veo bien 
![image](https://github.com/janis-commerce/ui-web/assets/57736533/f9f18b77-1a09-494c-953e-5d72d04bc640)
![image](https://github.com/janis-commerce/ui-web/assets/57736533/7a85a9b6-00fc-44b6-913c-394b1183e64c)

2024-02-16 15:52 UTC, Mauroskyer approved these changes

2024-02-16 19:30 UTC, colomfernando commented
@dgiannico19 seria mejor poner el color default en blue tal cual lo usamos en views. Por otro lado, viendo en views y aca, si definimos un boton como cleaned o outlined, se deja un background trasnparente, pero en storybooks se esta viendo un gris  

![image](https://github.com/janis-commerce/ui-web/assets/21691590/f5f4cc62-fa06-4d68-8cb1-46e82de33e00)

2024-02-16 21:32 UTC, dgiannico19 commented
Perfecto @colomfernando ahi lo corregi y lo mande nomas! gracias

2024-02-19 12:36 UTC, colomfernando approved these changes

2024-02-19 12:36 UTC, merged