Generic map component
janis-commerce/ui-web pull request #52
Opened 2024-12-26 21:01 UTC by FranciscoZapa

Link al ticket
https://janiscommerce.atlassian.net/browse/JMV-3615

Descripción del requerimiento
Se requiere llevar el componente Map a UI-web y replantear cosas que quedaron mal en el componente original de views

NECESIDAD

Se busca crear un componente Map que sea agnostico, no debe contener logica que un mapa normal no tendria

Cosas a evitar:

Que haya logica muy atada a views como themes, condicionales, schemas, procesamiento de marcadores en base a data

Armar componentes con logica de views que incluye los puntos anteriores

Definir marcadores en base a data de views como por ejemplo creacion rutas v2

Cosas a incluir:

Limpiar props innecesarias

Simplificar el componente

La data que le llega se entiende que ya esta procesada por lo que se debe mostrar como le llegue, para esto se debe definir bien lo que debe llegarle por props (armar tabla de propiedades)

Mejorar codigo de funcionalidades que se mantienen pero su codigo es poco legible

El componente debe permitir las mismas funcionalidades que tiene ahora

Descripción de la solución
Se crearon los componentes necesarios para mostrar las caracteristicas requeridas
Se limpio la logica que armaba cosas atadas a views para obtenerlas directamente por props
Se instalaron librerias necesarias para el funcionamiento del mapa
Se separaron muchas funciones en archivos de utils para achicar codigo
Se movieron todos los componentes a la carpeta components dejando solo map.js como componente base
Se documentaron las props para tener una buen entendimiento de que hace cada una
Deje codigo comentado que servira cuando implemente el setMarker

¿Cómo se puede probar?
Levantando la rama actual

Corriendo el comando yarn storybook
Ingresando a la tag [Map/OnlyMap](http://localhost:6006/?path=/story/components-map--only-map&args=googleMapsApiKey:AIzaSyDGeRGWLpDSS0C9XPevsg5LruKx2wCA9W4)
El link ya tiene agregada la api key funcional

En Map.stories.js dentro del codigo agregar markersMockCreationStep o markersMockShippingStep que dejo debajo para ir viendo como se ven los casos requeridos y actuales con el mapa nuevo
Reemplazar el mock de markers en baseArgs para usarlos

Jugar agregando mas markers o cambiando configuraciones para probar que todo vaya bien y como se espera

Mocks: Dejo los archivos json

[markersMockCreationStep.json](https://github.com/user-attachments/files/18169052/markersMockCreationStep.json)
[markersMockShippingStep.json](https://github.com/user-attachments/files/18169053/markersMockShippingStep.json)

Screenshot
Multirutas
![image](https://github.com/user-attachments/assets/d3b2724a-a4dd-4009-8cfb-c6e07f703fb7)

Shipping step mock
![image](https://github.com/user-attachments/assets/aee42854-f5f5-4c7b-9b85-d84338b1059e)

Creation step mock
![image](https://github.com/user-attachments/assets/bde3cf36-7102-446a-9aee-d45417e028ff)

2024-12-27 13:31 UTC, dgiannico19 requested changes
@FranciscoZapa te pase los comentarios de la ora rama y te agrego que falta subir el `yarn.lock`, tene en cuenta que a master suben ahí las dependencias nuevas

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/Map.js
> +		if (map) {
aca @FranciscoZapa  no se podría aplicar el retorno a la inversa?
`if (!map) return`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/Map.js
> +			mapRef.current = map;
@FranciscoZapa es necesario volver a hacer `mapRef.current = map` como 2 lineas arriba? yo `consologuee` y me da siempre el mismo valor

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/Map.js
> +			const fullScreenPos = showSearchBar ? 'RIGHT_BOTTOM' : 'RIGHT_TOP';
@FranciscoZapa  se podría declarar afuera de la función esta constante no?

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/Map.js
> +	markers: PropTypes.arrayOf(
@FranciscoZapa  aca la consola nos tira errores, esto se da porque `arrayOf` espera que le mandes `shape({}) `para el interno en lugar de `arryof` de `arrayof`
el `markers` completo quedaría asi:
`markers: PropTypes.arrayOf(
		PropTypes.shape({
			drawRoute: PropTypes.bool,
			points: PropTypes.arrayOf(
				PropTypes.shape({
					position: PropTypes.shape({
						lat: PropTypes.number,
						lng: PropTypes.number
					}),
					icon: PropTypes.object,
					overlay: PropTypes.element,
					infoWindowChildren: PropTypes.element
				})
			),
			polylineOptions: PropTypes.shape({
				strokeColor: PropTypes.string,
				strokeOpacity: PropTypes.number,
				strokeWeight: PropTypes.number
			})
		})
	),`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/components/MarkersDrawer/MarkersDrawer.js
> +						key={idx}
@FranciscoZapa  Acá tené en cuenta que el `index` del` .map `no se recomienda usar como key, podrías pasarlo a `string` como hacemos en `Views`, tipo `${idx.toString()}` o ver que otro dato llega en `marker` a ver si se puede usar

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/components/Route/Route.js
> +					key={idx}
@FranciscoZapa Acá tené en cuenta que el `index` del `.map` no se recomienda usar como key, podrías pasarlo a `string` como hacemos en `Views`, tipo `${idx.toString()}` o ver que otro dato llega en `points` a ver si se puede usar

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/components/Route/Route.js
> +		points: PropTypes.arrayOf({ lat: PropTypes.number, lng: PropTypes.number }),
@FranciscoZapa  error de tipo en consola por lo mismo, seria algo asi en este caso:
`points: PropTypes.arrayOf( PropTypes.shape({ position: PropTypes.shape({ lat: PropTypes.number, lng: PropTypes.number }) }) ),`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getDirections.js
> +
@FranciscoZapa  esto para todas las funciones no solo para esta, estaría bueno exportarlas todas por default en lugar de un `export const `ya que van solas en cada archivo y documentar con `JSDoc` como hacemos en `Views` para explicar que hace, parámetros y retorno, por ej

`/**
 * Descripcion en ingles
 *
 * @param {tipo de dato} parametro 1 - descripcion parametro 1
 * @param {tipo de dato} parametro 2 - descripcion parametro 2
 * @returns {tipo de dato} - descripcion de lo que devuelve
 */`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getMapOptions.js
> +	const mapOptions = {
@FranciscoZapa  Aca usaría un `format` también asi separamos responsabilidades
![image](https://github.com/user-attachments/assets/e9108488-5416-400d-889b-b43358155746)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +
@FranciscoZapa  Estas variables las declararía en mayúscula y `SNAKE_CASE` ya que no cambiarán en ningún momento, también aprovecharía para verificar si no corresponde mandarlas al archivo `constants`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +	try {
@FranciscoZapa Creo que varias cosas se pueden sacar afuera del `try`, la idea es que `catchee` los errores del `post` nomas?

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +		const allWaypoints = [
Acá se podría sacar una función
`const allWaypoints = getAllWaypoints(origin, destination, waypoints);`
![image](https://github.com/user-attachments/assets/588f4865-e91a-4a9c-880d-69ef7159c393)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +			waypointsSubset = [
@FranciscoZapa  Acá también un formateador
`waypointsSubset = formatWaypoints(waypointsSubset);`
![image](https://github.com/user-attachments/assets/93eb8d63-4bd0-48ec-811a-8d0a49f5d875)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +			const body = {
@FranciscoZapa Acá podríamos usar un `format` no? tipo 
`const body = formatBody(waypointsSubset);`
y una función que formatee:
![image](https://github.com/user-attachments/assets/05bc4eb8-0c16-4dd9-80d5-06d6f5983e30)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/getPolylineDirections.js
> +			const header = {
@FranciscoZapa acá también 
`const header = getHeaders(googleMapsApiKey);`
y una función que lo haga
![image](https://github.com/user-attachments/assets/480db8d0-81d0-4f0c-b052-1a2e8acd3fd4)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/mapConstants.js
@FranciscoZapa  lo llamaría `constants.js` al archivo por convención y usaría mayúsculas y `SNAKE_CASE`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/parseCoordsForPolylines.js
> +	const validPickupLoc = validLock(origin);
@FranciscoZapa a que refiere `loc`? y `lock`? 
Si es sobre `locations` sacaría la `k` de `validLock`, si es sobre cerrado agregaría la `k` en las constantes

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/setCenterByGeolocationOrCenter.js
> +const { setCoordinatesForGeolocation } = require('./setCoordinatesForGeolocation');
@FranciscoZapa  usaste `require` por algo en especial?

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/setCenterByGeolocationOrCenter.js
> +const isValidCenter = (center) => {
@FranciscoZapa Que pasa si viene` center. lat` pero no `center.lng`? falta un return al final, yo destructuraría y validaría directo
![image](https://github.com/user-attachments/assets/ffd6b7f8-67a4-42dd-a8f2-9130b70ac58c)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +const findName = (result, type) => {
@FranciscoZapa que devuelve acá si no incluye el `type`? xq abajo se usa directo y acá entiendo que puede pasar eso, igualmente invertiría la validación:
![image](https://github.com/user-attachments/assets/e684f8d1-7250-4a95-b80a-f889a8fcd672)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +	const places = await getPlaces(latLng);
@FranciscoZapa Acá no deberíamos encerrarla en un `try catch`?
Además, todo lo que va estando dentro de los `if`, lo sacaría a funciones
por ej:
![image](https://github.com/user-attachments/assets/b75f786f-d587-4102-b4d6-02069a4cc25b)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +	allRules.forEach((rule) => {
@FranciscoZapa esto lo sacaría a una función

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +		.map((waypoint) =>
@FranciscoZapa Acá no se podría ejecutar directamente la función `format`? y que en ella si no llega algo retorne `null`? Quedaría asi:
![image](https://github.com/user-attachments/assets/d5379206-5528-4945-a513-03eb572d1458)

![image](https://github.com/user-attachments/assets/9a1de991-fc3a-460d-ae88-6235a4c8a610)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +export const findSelectedPosition = (selectedRows, marker) => {
@FranciscoZapa como ves algo asi?
![image](https://github.com/user-attachments/assets/66e56b83-06b0-4281-803f-aa7ce9059995)

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +	markers.map((marker) => {
@FranciscoZapa  podemos destructurar directo `lat` y `lng` no?

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +	if (markers.length) {
@FranciscoZapa Acá no podrías validar al revés arrancando con un
`if (!markers.length) return null`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/utils.js
> +		map.setCenter(centerCoordinate);
@FranciscoZapa aca esta función esta tirando un error
`main.js:164 InvalidValueError: setCenter: not a LatLng or LatLngLiteral with finite coordinates: in property lat: NaN is not an accepted value
`
me parece que deberías validar `lat` y `lng` antes de setear el mapa ya que están llegando en `Nan`

2024-12-27 13:31 UTC, dgiannico19 commented on src/components/Map/utils/validateCoordinates.js
> +const validateCoordinates = (region) => {
Consulta @FranciscoZapa viendo que solamente se usa `lat` y `lng`, y las validaciones recaen sobre ellos tmb, no se podría destrucuturar y usarlos para validar directo? Ojo no probé no se si el válido
![image](https://github.com/user-attachments/assets/30755635-efea-46d7-82e8-11beb3250291)

2024-12-27 21:47 UTC, FranciscoZapa commented on src/components/Map/Map.js
> +			const fullScreenPos = showSearchBar ? 'RIGHT_BOTTOM' : 'RIGHT_TOP';
me parece que no da para constante porque es una funcion y para sacarla aparte en una funcion tampoco creo porque igual seria una linea, creo que si esta legible asi

2024-12-27 21:49 UTC, FranciscoZapa commented on src/components/Map/utils/utils.js
> +export const findSelectedPosition = (selectedRows, marker) => {
esta genial el cambio solo mantengo el destructuring dentro de la funcion para saber de donde viene type id y shipping id

2024-12-27 21:52 UTC, FranciscoZapa commented on src/components/Map/utils/validateCoordinates.js
> +const validateCoordinates = (region) => {
Aca tome tu idea y lo mezcle con lo anterior queda mas legible pero igual mantengo el destructuring dentro ya que si esta bien validar que exista y que sea objeto region, sino si llega null o undefined rompe, mejor que quede validado

2024-12-27 21:55 UTC, FranciscoZapa commented on src/components/Map/utils/getPolylineDirections.js
> +	try {
aca hay dos errores uno cuando se cumple el if y otro en axios entonces creo que queda todo dentro

2024-12-27 21:56 UTC, FranciscoZapa commented on src/components/Map/utils/parseCoordsForPolylines.js
> +	const validPickupLoc = validLock(origin);
dejo todo con location

2024-12-27 21:56 UTC, FranciscoZapa commented on src/components/Map/utils/setCenterByGeolocationOrCenter.js
> +const { setCoordinatesForGeolocation } = require('./setCoordinatesForGeolocation');
jajaja rarisimo ya se lo vole

2024-12-27 21:57 UTC, FranciscoZapa commented on src/components/Map/utils/setCenterByGeolocationOrCenter.js
> +const isValidCenter = (center) => {
ahi mejore mezclando tu idea con lo que estaba

2024-12-27 22:03 UTC, FranciscoZapa commented on src/components/Map/utils/utils.js
> +	allRules.forEach((rule) => {
me parece que no da para funcion aparte, porque el foreach busca si alguna regla de la lista esta en mapFeatureTypes para devolver los estilos entonces la funcion completa ya hace un get de estilos de mapa, para mi todo es una sola cosa

2024-12-30 13:24 UTC, dgiannico19 commented on src/components/Map/Map.js
> +			const fullScreenPos = showSearchBar ? 'RIGHT_BOTTOM' : 'RIGHT_TOP';
@FranciscoZapa ojo yo aca te hablaba solamente de `fullScreenPos`, declararla fuera de la funcion, igual como te parezca

2024-12-30 14:08 UTC, dgiannico19 commented on src/components/Map/Map.js
> +						//setMarker={setMarker}
@FranciscoZapa aca viajó un comentario

2024-12-30 14:10 UTC, dgiannico19 commented on src/components/Map/components/Locations/Locations.js
@FranciscoZapa Se cambiaba el nombre del archivo al final?

2025-01-02 12:52 UTC, dgiannico19 commented
@FranciscoZapa veo que rebota algún `check` del PR y no esta apto para mergear, es posible que tengas que `pullearte` master?

2025-01-02 12:58 UTC, dgiannico19 commented on src/components/Map/utils/getAllWaypoints.js
> +const getAllWaypoints = (origin, destination, waypoints) => {
Aca se podría mandar implícito el return 

`const getAllWaypoints = (origin, destination, waypoints) => [
	formatCoordinates(origin.lat, origin.lng),
	...createLatLngObjectsFromArray(waypoints),
	formatCoordinates(destination.lat, destination.lng)
];
`

2025-01-02 13:02 UTC, dgiannico19 commented on src/components/Map/components/Marker/utils.js
> +
@FranciscoZapa en este archivo, estamos manejándolo de la manera vieja, un archivo con mil funciones dentro, entiendo que la idea es romper con eso creando un archivo por función y todas bien documentadas con jsDoc

2025-01-02 15:20 UTC, FranciscoZapa commented
@colomfernando @dgiannico19 @Sebaavt95 ya estan corregidos todos los comentarios de dami, aparte agregue un fix para que no se vea el console.error de ErrorBouundary en los test ya que se veia como que estuviera roto algo

2025-01-02 17:42 UTC, colomfernando commented on src/components/Map/Map.js
> +		setCenterByMarkers(mapRef, markers, center, firstLoad, setFirstLoad);
no me convence tener un firtLoad y menos usando un useState. Podriamos tener el useEffect con dependencias vacias. Como minimo deberia ser un useRef para evitar render innecesarios, pero realmente necesitamos esa variable?

2025-01-02 17:49 UTC, colomfernando commented on src/components/Map/utils/utils.js
> +import { intersection } from 'lodash';
no me convece este utils.js con todo tirado..haria un archivo por funcion para que sea mas facil en el futuro escalar y debbuggear. Ademas, hay utils que podrian ser mas genericas para el uso en todo el repo como por ejemplo isObject o promisewrapper

2025-01-02 20:43 UTC, colomfernando requested changes

2025-01-02 20:43 UTC, colomfernando commented on src/components/Map/Map.js
> +		setCenterByGeolocationOrCenter(markers, setCoords, center);
esta funcion tiene una responsabilidad muy igual a la de abajo. En base a lo que hablamos, replanteamos esto para poder desarmar en funciones mas chicas cada cosa que necesitemos. Por ejemplo, en base a marcadores, centro o ubicacion del usuario, poder obtener lat y lng del centro. con esa info podemos centrar el mapa usando la referencia del mapa y dejamos de tener una funcion con 5 argumentos

2025-01-02 20:50 UTC, colomfernando requested changes

2025-01-02 20:50 UTC, colomfernando commented on src/components/Map/utils/formatBody.js
> +const formatBody = (waypointsSubset) => {
no estamos validando basicamente nada en esta funcion. Segundo formatBody de que seria..? no seria mejor formatWaypoints si buscamos eso?

2025-01-02 20:50 UTC, colomfernando commented on src/components/Map/Map.js
> +	saveRouteData,
esta prop tuve que ir hasta donde se usa para entender que era un callback, tenemos que mejorar el nombre

2025-01-02 20:50 UTC, colomfernando commented on src/components/Map/components/MarkersDrawer/MarkersDrawer.js
> +					<Locations key={idx} {...commonProps} markers={marker.points} />
no le veo sentido a tener Locations cuando es iterar sobre marcadores. Podemos eliminar el componente Location para iterar directamente sobre los marcadores

2025-01-03 18:31 UTC, colomfernando requested changes

2025-01-03 18:31 UTC, colomfernando commented on src/components/Map/utils/getPolylineDirections.js
> +		for (let i = 0; i < numRequests; i++) {
simplificar esta funcionalidad en pequeñas partes. El objtivo seria tener una fucnion que en base a un array de polylines y un limite ya me devuelva array de array ya armados para poder iterar y realizar dicha request

2025-01-03 18:31 UTC, colomfernando commented on src/components/Map/utils/parseCoordsForPolylines.js
> +	const destination = coords[coords.length - 1].position;
refactorizar para no tener variables creadas sin sentido

2025-01-03 18:31 UTC, colomfernando commented on src/components/Map/components/Locations/Locations.js
> +const Locations = ({ readOnly, setMarker, markers }) => {
Este componente pasaria a llamarse Markes y tendra la responsabilidad de tener su componente Marker, siendo siempre MArkers el que lo usaria

2025-01-03 18:31 UTC, colomfernando commented on src/components/Map/components/InfoWindow/InfoWindow.js
> +const InfoWindowComponent = ({ infoWindowHandles, data, children }) => {
este componente lo usaria solo Marker, por tal motivo iria dentro de dicha carpeta

2025-01-03 18:31 UTC, colomfernando commented on src/components/Map/components/SearchBox.js
> +import React, { useRef } from 'react';
armar capeta con su index.js

2025-01-03 18:31 UTC, closed without merging

2025-01-03 18:31 UTC, colomfernando commented
Se declina el pr, dejamos comentarios